language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-22
    - ANDROID_ABI=armeabi-v7a
android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.3
    - android-23
    - extra-android-m2repository
    - $ANDROID_TARGET
    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
script:
  - echo "running ktlint"
  - ./gradlew ktlint
  - echo "running test"
  - ./gradlew clean testDebugUnitTestCoverage
  # Renaming folder and files of reports so codecov.io can find it
  - mv app/build/reports/jacoco/testDebugUnitTestCoverage app/build/reports/jacoco/jacocoTestDebugUnitTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)

