{
  "ignore": [
    "(?s:.*/android/.*)\\Z"
  ],
  "codecov": {
    "notify": {},
    "require_ci_to_pass": true
  },
  "comment": {
    "layout": "header, diff",
    "behavior": "default",
    "require_changes": false
  },
  "parsers": {
    "gcov": {
      "branch_detection": {
        "loop": true,
        "macro": false,
        "method": false,
        "conditional": true
      }
    }
  },
  "coverage": {
    "range": [
      70,
      100
    ],
    "round": "down",
    "status": {
      "patch": true,
      "changes": false,
      "project": true
    },
    "precision": 2
  }
}